### PR TITLE
Revert "Have all AI chat calls use same code path and UX"

### PR DESCRIPTION
**Pull request by tarasglek**
Reverts tarasglek/chatcraft.org#155

This caused
```
> chatcraft.org@0.0.0 build /Users/taras/Documents/chatcraft.org
> tsc && vite build

src/components/Message/MessageBase.tsx:157:17 - error TS2540: Cannot assign to 'text' because it is a read-only property.

157         message.text = text;
                    ~~~~

src/components/Message/NewMessage.tsx:17:8 - error TS2739: Type '{ key: string; message: ChatCraftAiMessage; chatId: string; isLoading: true; heading: string; }' is missing the following properties from type 'Omit<MessageBaseProps, "message" | "avatar">': editing, onEditingChange

17       <OpenAiMessage
          ~~~~~~~~~~~~~

src/lib/ChatCraftMessage.ts:194:10 - error TS2540: Cannot assign to 'text' because it is a read-only property.

194     this.text = text;
             ~~~~


Found 3 errors in 3 files.

Errors  Files
     1  src/components/Message/MessageBase.tsx:157
     1  src/components/Message/NewMessage.tsx:17
     1  src/lib/ChatCraftMessage.ts:194
 ELIFECYCLE  Command failed with exit code 2.
 ```

### CODE REVIEW

**Comment by humphd** [comment]
This error isn't from that change.  You're hitting the regression I mentioned in #156 with [your update to langchainjs v0.0.v105](https://github.com/tarasglek/chatcraft.org/pull/161/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27), which includes them reworking a bunch of stuff.

I'm going to isolate our code from langchain's so we don't break when they update.
